application:
  subdomain: minne
  upstreams:
    - location: /
      backend: http://minne:3000/
services:
  surrealdb:
    # upstream: surrealdb/surrealdb:v2.7.0
    image: docker.1ms.run/surrealdb/surrealdb:v2.7.0
    user: root
    environment:
      - SURREALDB_USERNAME=lazycat
      - SURREALDB_PASSWORD={{ stable_secret "db_password" }}
      - SURREALDB_DATABASE=minne
      - SURREALDB_NAMESPACE=minne
    command: start --log info --user lazycat --pass {{ stable_secret "db_password" }} rocksdb:/database/database.db
    binds:
      - /lzcapp/var/database:/database
  minne:
    # upstream: ghcr.io/perstarkse/minne:v1.0.5
    image: ghcr.1ms.run/perstarkse/minne:v1.0.5
    user: appuser
    environment:
      - SURREALDB_ADDRESS=ws://surrealdb:8000
      - SURREALDB_USERNAME=lazycat
      - SURREALDB_PASSWORD={{ stable_secret "db_password" }}
      - SURREALDB_DATABASE=minne
      - SURREALDB_NAMESPACE=minne
      - OPENAI_BASE_URL={{.U.open_ai_base_url}}
      - OPENAI_API_KEY={{.U.openai_api_key}}
      - DATA_DIR=/data
      - HTTP_PORT=3000
      - RUST_LOG=info
      - RERANKING_ENABLED={{.U.reranking_enabled}}
    command: sh -c 'echo "Waiting for SurrealDB to start..." && sleep 10 && echo "Starting application..." && /usr/local/bin/main'
    binds:
      - /lzcapp/var/data:/data
    depends_on:
      - surrealdb
